# yaml-language-server: $schema=https://json.schemastore.org/hugo.json
baseURL: https://znd4.dev
languageCode: "en-us"
title: "lost in the math"
theme: PaperMod

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  defaultTheme: "dark"
  disableThemeSwitchToggle: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  author: ["Zane Dufour"]

  editPost:
    URL: https://github.com/znd4/blog/tree/main/content/
    Text: "Suggest Changes"
    appendFilePath: true

  profileMode:
    enabled: true
    title: Zane Dufour
    subtitle: Perennial novice. neovim enjoyer. Begrudging jupyter user.
    buttons:
      - name: Blog
        url: posts
  socialIcons:
    - name: "github"
      url: "github.com/znd4"
    - name: "reddit"
      url: "reddit.com/u/zdog234"
