baseURL = 'znd4.dev'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[params.social]]
key = 0
name = 'github'
url = "github.com/znd4"

[[params.social]]
key = 1
name = 'reddit'
url = "reddit.com/u/zdog234"


[module]
[[module.imports]]
path = 'github.com/LordMathis/hugo-theme-nightfall'
